---
cloud_service_group: Compute
cloud_service_type: Server
name: Count by Type
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: data.server_instance_type.code_name
        fields:
          - name: value
            operator: count
options:
  chart_type: DONUT