---
cloud_service_group: Compute
cloud_service_type: Volume
name: Count By Type
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: data.block_storage_type
        fields:
          - name: value
            operator: count
options:
  chart_type: DONUT