---
cloud_service_group: Compute
cloud_service_type: Volume
name: Total Volume Size
query:
  aggregate:
    - group:
        fields:
          - name: value
            key: data.block_storage_size
            operator: sum
options:
  value_options:
    key: value
    type: size
    options:
      default: 0
      source_unit: Byte
