---
cloud_service_group: Storage
cloud_service_type: Nas
name: Total Memory Size
query:
  aggregate:
    - group:
        fields:
          - name: value
            key: data.volume_size_gb
            operator: sum
options:
  value_options:
    key: value
    type: size
    options:
      default: 0
      source_unit: GB
