---
cloud_service_group: EC2
cloud_service_type: Instance
name: Count By Instance Type
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: instance_type
        fields:
          - name: value
            operator: count
options:
  chart_type: TREEMAP
  name_options:
    key: name
