---
cloud_service_group: Networking
cloud_service_type: Load Balancer
name: Count By Type
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: data.load_balancer_network_type
        fields:
          - name: value
            operator: count
options:
  chart_type: DONUT