---
cloud_service_group: Database
cloud_service_type: CloudDB
name: Total Cpu Count
query:
  aggregate:
    - group:
        fields:
          - name: value
            key: data.cpu_count
            operator: sum
options:
  value_options:
    key: value
    options:
      default: 0
